#!/usr/bin/php
<?php

use App\Cores\Migrate;

error_reporting(E_ALL);
ini_set('display_errors', 'On');

define("ROOT", __DIR__);

require_once ROOT . '/vendor/autoload.php';
$dotenv = \Dotenv\Dotenv::createImmutable(ROOT);
$dotenv->load();

$options = $_SERVER['argv'];

if (!isset($options[1])) {
    exit('Bye!\n');
}

if (isset($options[1]) && $options[1] === 'migrate') {
    $app = new \App\Cores\Application([]);
    $app->migrate = new Migrate();
    $app->migrate->apply();
}

if ($options[1] === 'serve') {
    $output = null;
    $code = null;
    exec('php -S localhost:8888 public/index.php', $output, $code);
}
